# Generated by Django 4.2.6 on 2023-10-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_usersunverified_alter_users_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersUnverified',
        ),
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
